### ISSUE TITLE
Order project dropdown list by most recent usage

### ISSUE THREAD

**Issue by richeterre** [futurice/hours-ui#10]

**Comment by phadej** [comment]
List whcih changes order on itself (once-in-a-while) would most likely cause a confusion (i.e. hard to find something *not recent* when you need it)

We talked with @janivihervas, that we rather add a quick links/buttons to directly select recent project (/ task), so you don't even need to open dropboxes. It might make UI a bit "bigger", but IMHO productivity gain is worth it. 

What you think about?

**Comment by richeterre** [comment]
That could work as well ☺️ The reason I filed this was that I usually have to browse through a long and seemingly unordered list of active and inactive projects to find the one I need. Not sure why inactive ones show up there at all, as I can't do anything with them.

**Comment by phadej** [comment]
True. The project lists could be at least alphabetically sorted!

**Comment by pahuttun** [comment]
There is a use case where people doing lots of misc stuff does have dozens and dozens of projects. They are not inactive, but 95% of hour markings go to 5-10 most used projects and sometimes you need the rest 50 projects.

So alphabetic order wouldn't be that good as the most used won't be at top. Maybe possibility to mark some projects as "favourite" so they would be sorted before alphabetic sort? Or easy way to hide (and unhide) some projects?

**Comment by phadej** [comment]
I'm not sure how arbitrary order of 50 projects would be better than full alphabetical search.

With "min 1 hour" -marking policy, 50 projects would spawn over two weeks. That feels like very exceptional case. 

I'd suggest taking a screenshot of your current futuhours view (say for the last two month), and send it to *Alisa*, so she could think about your usage pattern as well.

**Comment by phadej** [comment]
ping @pahuttun ^

**Comment by janivihervas** [comment]
How about list the x recent projects on top, and the rest on alphabetical order? Or just sort all of them based on recent usage? There is searching implemented so that could help with a very long project list. And the form is automatically using the most recent values, so marking a full day with same data as the most recent marking takes two clicks: open the form and save.

Current implementation (fake data):
![screen shot 2016-07-21 at 13 07 55](https://cloud.githubusercontent.com/assets/6649492/17019465/1ceaed34-4f45-11e6-9d13-54ddec76d88d.png)

**Comment by pahuttun** [comment]
If the UI would be somehow personalizable, I mean some kind of option to tell if you want alphabetic or usage sorted, that would fit us all.

If that is not feasible, then we have to remember that...
- The solution should fit the best those people, who do billable work (as it is more critical to not mark billable hours than non-billable)
- The solution should fit the best largest amount of people even if it means that there are few special use cases which wouldn't benefit from it
- People with peculiar use cases, like me, already have to spend like 15-30 minutes every day to think how they mark their hours. It doesn't matter that much if I have to spend 3 minutes more because of awkward UI

But with that said, personally I would love combination of "most used first", then some kind of visual sign to tell you that alphabetic order starts from here and after that, everything (including those which were suggested first) would be in alphabetic order.

Then usually I should find my projects easily from top of the list and when I've done 1-2 hours some other stuff, it should be easily browsable because of alphabetic sort or searchable, if I already remember what the name was.

**Comment by pahuttun** [comment]
If the order is only "most used first", it is really hard to find anything after the list grows to be scrollable. But if the order is only "alphabetical", then it would be frustrating to change your project every time if the first project is not the most used one.

So if you have to choose only one option, "most used first" probably fits the more usecases. However that will be awkward for us with lots of projects.

This shows the problem with current Futuhours.

![image](https://cloud.githubusercontent.com/assets/4655211/17020104/8435751a-4f48-11e6-865c-7d8921e967ed.png)

There are also two ways to decrease the need of scrolling and browsing:
- Instruct people how to quickly add and remove projects from Futuhours, so if you need to mark few hours to some special project you would add it, mark hours and then remove it
- Way to temporarily increase the size of box which shows projects (as I've done in screenshot). If you have 10-20 projects and box only shows 6, sometimes you just want to see all of them without scrolling so you would remember which was the name of that one project in which I need to mark my hours.

**Comment by phadej** [comment]
@pahuttun note, this is public repository.

**Comment by phadej** [comment]
Also unrelated note: remember mobile interface too.

**Comment by janivihervas** [comment]
@richeterre, @pahuttun:  How's this for a solution: show the 3 most recently used projects and tasks on top and the rest on alphabetical order. The number of the most recent is easily configurable, though not in the UI.

Projects:
![screen shot 2016-08-05 at 10 15 04](https://cloud.githubusercontent.com/assets/6649492/17429196/07842d18-5af6-11e6-9404-e3da4c9425c2.png)
Tasks:
![screen shot 2016-08-05 at 10 16 27](https://cloud.githubusercontent.com/assets/6649492/17429195/0783a0a0-5af6-11e6-9457-37b2eab4ec99.png)
Search:
![screen shot 2016-08-05 at 10 16 50](https://cloud.githubusercontent.com/assets/6649492/17429197/0784becc-5af6-11e6-8d42-d4382fae4a0a.png)
![screen shot 2016-08-05 at 10 25 44](https://cloud.githubusercontent.com/assets/6649492/17429361/0977f4f0-5af7-11e6-9445-11ec360c9c5e.png)
![screen shot 2016-08-05 at 10 24 52](https://cloud.githubusercontent.com/assets/6649492/17429340/ece97e1c-5af6-11e6-8b17-a0ea393db4ed.png)

Projects (the 2 most recent):
![screen shot 2016-08-05 at 10 19 55](https://cloud.githubusercontent.com/assets/6649492/17429303/b03d1974-5af6-11e6-8ec6-974fb1ea92fc.png)

**Comment by phadej** [comment]
Looks great. I'd make it 5 by default. Does it pick the most used task from that project when you pick it?

**Comment by janivihervas** [comment]
Thanks and can do. Lets see how the 5 most recent works when this is in production, and adjust accordingly. 

Yes, the default task is the most recently used in the project. I'm assuming that the list of projects and the tasks in the projects from API are sorted based on recent usage.

**Comment by phadej** [comment]
That was my next question, :+1: for trusting backend on the order.

**Comment by janivihervas** [comment]
Modifications: 
 - Show closed projects and tasks, that are assigned to the user. Reason: if a project or task is closed prematurely, the user is notified of this and he/she doesn't have to wonder why the project/task is not visible any more. UI hides projects and tasks that are closed and have the latest entry from over two months ago. This list is specific to the day and the UI needs every user assigned project and task, so that's why this is not done in the backend. 
 - Group other projects and tasks for better visual presentation

Can this issue be closed now, @richeterre, @pahuttun? 

![screen shot 2016-08-09 at 12 57 29](https://cloud.githubusercontent.com/assets/6649492/17512555/0b969902-5e31-11e6-82c8-7aee06515902.png)

**Comment by richeterre** [comment]
👏  :shipit:
