### ISSUE TITLE
636363 is too light color for the plain text

### ISSUE THREAD

**Issue by phadej** [futurice/hours-ui#39]

**Comment by phadej** [comment]
![image](https://cloud.githubusercontent.com/assets/51087/23771661/8da78474-0520-11e7-9aea-cdeeba086517.png)

Have to check on OSX, but might be related to too light font

**Comment by janivihervas** [comment]
I sure that that is not the disabled color, because it looks awfully like that.

Disabled:
![image](https://cloud.githubusercontent.com/assets/6649492/23785178/0e68f798-056f-11e7-8a4c-73d5a25799cf.png)

Enabled:
![image](https://cloud.githubusercontent.com/assets/6649492/23785194/1c464bc2-056f-11e7-99ea-37f74535138e.png)

**Comment by phadej** [comment]
It's not disabled, as I can edit it.

**Comment by phadej** [comment]
![image](https://cloud.githubusercontent.com/assets/51087/23785659/755fa24c-0571-11e7-880f-b46a62b72a50.png)

**Comment by phadej** [comment]
I.e. i suspect that the font is too light, and linux (or chrome) font rendering cannot cape with it.

**Comment by phadej** [comment]
![image](https://cloud.githubusercontent.com/assets/51087/23785985/0f5a3b22-0573-11e7-90e7-b5b77bd1a6f9.png)

last one has `font-weight: normal;` on `.entry-show`
